export const CarrefourCategories = {
	mainFoodCarrefour: [
		'healthyFoodCarrefour',
		'worlsFoodCarrefour',
		'breakfastCarrefour',
		'cannedCarrefour',
		'preservesCarrefour',
		'spicesCarrefour',
		'souces',
		'loose',
		'sugarCarrefour',
		'snacsCarrefour',
		'sweets',
		'dessertsCarrefour',
		'coffeeCarrefour',
		'bakeryCarrefour',
		'sweetBakeryCarrefour',
	],
	diaryCarrefour: [
		'milkCarrefour',
		'butterCarrefour',
		'cheeseCarrefour',
		'cottageCarrefour',
		'dairyCarrefour',
		'babyDairyCarrefour',
		'eggsCarrefour',
		'tofuCarrefour',
		'yeastCarrefour',
	],
	drinksCarrefour: [
		'softDrinksCarrefour',
		'lemonadeCarrefour',
		'fruitDrinksCarrefour',
		'energizersCarrefour',
		'sportDrinksCarrefour',
		'teaDrinksCarrefour',
	],
	drogeryCarrefour: [
		'toiletPaperCarrefour',
		'laundryCarrefour',
		'cleaningCarrefour',
		'wcCarrefour',
		'hygieneCarrefour',
		'beautyCarrefour',
		'hairCareCarrefour',
		'perfumeCarrefour',
		'makeUpCarrefour',
		'healthCarrefour',
	],
	healthyCarrefour: ['noGlutenCarrefour', 'noLactoseCarrefour', 'bioCarrefour', 'dietFoodCarrefour', 'veganCarrefour'],
	readyDishesCarrefour: ['readyDishesCarrefour'],
	fruitsMainCarrefour: ['saladsCarrefour', 'vegetablesCarrefour', 'friutsCarrefour', 'nutsCarrefour', 'mashroomsCarrefour'],
	frostCarrefour: [
		'frostBakeryCarrefour',
		'frostIceCreamCarrefour',
		'frostVegetablesCarrefour',
		'frostFishCarrefour',
		'frostFriesCarrefour',
		'frostPizzaCarrefour',
		'frostReadyMealsCarrefour',
	],
	meatCarrefout: [
		'hamCarrefour',
		'sausagesCarrefour',
		'drySausagesCarrefour',
		'poultryCarrefour',
		'beefCarrefour',
		'porkCarrefour',
		'wildMeatCarrefour',
		'bioMeatCarrefour',
	],
	bakeryCarrefour: ['bakeryCarrefour', 'sweetBakeryCarrefour', 'frenchBakeryCarrefour', 'rollsCarrefour', 'breadCarrefour'],
	fishSeaFoodCarrefour: ['fishSeaFoodCarrefour'],
	babyCarrefour: [
		'babyToysCarrefour',
		'babyFoodCarrefour',
		'babyHygieneCarrefour',
		'babyCultureCarrefour',
		'babyArticlesCarrefour',
	],
	readyFoodsApetizersCarrefour: ['readyFoodsApetizersCarrefour'],
	forPets: ['petsDogCarrefour', 'petsCatCarrefour'],
	unusualShopping: ['electronicsCarrefour', 'homeGardenCarrefour', 'sportCarrefour', 'motoCarrefour'],
};
